// Generated by tools/physconst.py: the constants of the physics.
#ifndef PHYSCONST_H
#define PHYSCONST_H

// sizes in u (1 m = 1024):
#define R_WHEEL 410
#define R_HEAD 244
// the wheel is kept this much inside the ground (Belsosav):
#define BAND 5
// contact points closer are merged (Talppontegybeolvadasitav):
#define MERGE 102
// gravity in a step, with its fraction in 1/256:
#define G_INT 34
#define G_FRAC 158
// a volt (Loket) and what is left of it (Omegavalt):
#define LOKET 1819
#define OMEGAVALT 455
// a volt lasts 0.1 s (Ugroturelem*0.25):
#define VOLT_STEPS 14
// highest angular velocity of the driven wheel:
#define WHEEL_MAXW 16677
// separation speed limit, 0.01 m/s:
#define ELSZ 5
// 1 m/s:
#define VEL_1MS 476
// gas: 600 Nm, in 1/4 Nm:
#define GAS_TQ 2400
// the bike at the start, from its left wheel, in F:
#define F_BODY_X 222822
#define F_BODY_Y 157286
#define F_WHEELBASE 445644
#define F_RIDER_Y 272629
#define F_HEAD_Y 165150
// where the rider may be relative to the body:
#define SEAT_X -358
#define SEAT_Y 133
#define RIDER_TOP 492
#define RIDER_LEFT -512
#define RIDER_RIGHT 266

// Factors c as c*2^SH:
// the right wheel relative to the body, (0.85, -0.6) m, times cos and sin into u:
#define C_K_X 3482
#define C_K_X_SH 16
#define C_K_Y 2458
#define C_K_Y_SH 16
// wheel spring: K = 10000 N/m, wheel 10 kg; its length in r16:
#define C_SPRING_W 13848
#define C_SPRING_W_SH 16
// the same on the body of 200 kg:
#define C_SPRING_B 692
#define C_SPRING_B_SH 16
// its torque on the body (moment of inertia 200*0.55^2), from the sum of lever arm (u) x length (r16) >> 10:
#define C_SPRING_T 729
#define C_SPRING_T_SH 16
// damping between the wheels and the body: Sr = 1000 Ns/m:
#define C_FRIC_W 11908
#define C_FRIC_W_SH 14
#define C_FRIC_B 2382
#define C_FRIC_B_SH 16
// its torque, from the sum of lever arm (u) x velocity >> 10:
#define C_FRIC_T 2506
#define C_FRIC_T_SH 16
// the body angular velocity, for mulq14 with a lever arm << 4 (u):
#define C_OMS 12868
#define C_OMS_SH 12
// force of a wheel torque on the axle:
#define C_REACT 22688
#define C_REACT_SH 16
#define C_TWENTIETH 3277
#define C_TWENTIETH_SH 16
// brake: 1000 Nm/rad:
#define C_BRAKE_A 25133
#define C_BRAKE_A_SH 16
// and 100 Nms/rad, taken 0.7 times, so that a free wheel does not swing ever wider with a step this long (the game steps 0.003 s):
#define C_BRAKE_W 30257
#define C_BRAKE_W_SH 14
// a free wheel turning (moment of inertia 0.32):
#define C_FREE 14105
#define C_FREE_SH 14
// a wheel rolling around a contact point (moment of inertia 0.32 + 10*0.3975^2 there):
#define C_ROLL_W 13038
#define C_ROLL_W_SH 14
#define C_ROLL_T 18931
#define C_ROLL_T_SH 12
#define C_ROLL_DW 9502
#define C_ROLL_DW_SH 16
#define C_ROLL_V 20589
#define C_ROLL_V_SH 14
#define C_NEW 20861
#define C_NEW_SH 16
#define C_OLD 11832
#define C_OLD_SH 14
// the rider: rest 0.44 m above the body, moves every other step:
#define C_RREST 28836
#define C_RREST_SH 16
// its spring, 5 times as strong:
#define C_RIDER_S 6924
#define C_RIDER_S_SH 16
// its damping, 3 times as strong:
#define C_RIDER_F 14290
#define C_RIDER_F_SH 16
// the normal of the seat (-0.42, 0.91):
#define C_SEAT_NX 27847
#define C_SEAT_NX_SH 16
#define C_SEAT_NY 14831
#define C_SEAT_NY_SH 14
#define C_ELLIPSE 30247
#define C_ELLIPSE_SH 14
// the head relative to the rider, (0.09, 0.63) m:
#define C_H_X 369
#define C_H_X_SH 16
#define C_H_Y 2580
#define C_H_Y_SH 16

#endif
