"""The poses of the bike and the objects of test/snes_bike.c: writes
build/gen/bike_poses.h.

  bike_poses.py ELMA_RES OUT.h

The bike stands at the same place of level 1 (Warm Up) in every pose: at
rest, turned, at many angles, while turning, volting, with the rider and
the wheels moved, and near the edges of the screen; objects of every kind
around it.
"""

import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, '..', 'tools'))

import bikemodel as bm
import bikefix

HOLD = 3                     # frames a pose
LEVEL = 0
BASE = (30.0, -10.0)         # where the bike stands, meters from the origin
PPM = 4915 / 256

# Objects around the bike (type, anim, active, dx, dy meters):
OBJECTS = [
    (2, 0, 1, -4.0, 1.0), (2, 1, 1, 3.5, 2.0), (2, 0, 0, 1.0, 3.0),
    (3, 0, 1, 5.0, -2.0), (1, 0, 1, -5.5, -2.5), (4, 0, 1, 0.0, -1.5),
    (2, 1, 1, -6.4, 4.0), (2, 0, 1, 40.0, 0.0),
]


def origin(res_path):
    import elmadata
    import levgeom
    res = elmadata.Resource(res_path)
    lev = elmadata.internal_levels(res)[LEVEL]
    return levgeom.origin(lev)


def model_states():
    """(bikemodel.State, camera offset (pixels from centered)) of the
    poses, at the origin (0, 0)."""
    out = []
    rest = bm.State()

    def rotated(a, **kw):
        s = rest

        def R(p):
            return s.body + bm.rotate(p - s.body, a)
        return bm.State(body=s.body, body_a=a, wheel0=R(s.wheel[0]), wheel1=R(s.wheel[1]),
                        rider=R(s.rider), **kw)
    out.append((bm.State(), (0, 0)))
    out.append((bm.State(turned=True), (0, 0)))
    for k in range(24):
        a = k * 2 * math.pi / 24 + 0.05
        out.append((rotated(a, turned=bool(k & 1), wheel0_a=a * 3, wheel1_a=-a * 2), (0, 0)))
    for k in range(12):
        out.append((bm.State(turned=True, turn=k / 12 + 0.02), (0, 0)))
    for k in range(6):
        out.append((rotated(0.7, turned=False, turn=k / 6 + 0.04), (0, 0)))
    for v in (0.95, 0.8, 0.6, 0.4, 0.2):
        for v1 in (False, True):
            out.append((bm.State(volt=v, volt1=v1, turned=v1), (0, 0)))
    for dx, dy in ((0.1, 0.0), (-0.15, 0.05), (0.0, -0.1), (0.05, 0.1)):
        s = bm.State()
        out.append((bm.State(rider=(s.rider[0] + dx, s.rider[1] + dy)), (0, 0)))
    for d in (0.1, -0.08):
        s = bm.State()
        out.append((bm.State(wheel0=(s.wheel[0][0] + d, s.wheel[0][1] + d),
                             wheel1=(s.wheel[1][0] - d, s.wheel[1][1] + d)), (0, 0)))
    # Near the edges: the bike partly off the screen.
    for cam in ((115, 0), (-120, 0), (0, 100), (0, -96), (125, 95)):
        out.append((rotated(0.3, turned=True), cam))
    return out


def fixed_poses(org):
    """The poses as the program gets them (bikefix.State)."""
    out = []
    for st, (cx, cy) in model_states():
        st = st.moved(bm.v(org[0] / 65536 + BASE[0], org[1] / 65536 + BASE[1]))
        px = int((st.body[0] - org[0] / 65536) * PPM)
        py = int((org[1] / 65536 - st.body[1]) * PPM)
        out.append(bikefix.State.from_model(st, org, (px - 128 + cx, py - 112 + cy)))
    return out


def objects(org):
    """phys_objs: (type, anim, gravity, active, x, y) in 16.16."""
    out = []
    for t, anim, active, dx, dy in OBJECTS:
        x = org[0] + int(round((BASE[0] + 2.75 + dx) * 65536))
        y = org[1] + int(round((BASE[1] + 3.6 + dy) * 65536))
        out.append((t, anim, 0, active, x, y))
    return out


def main():
    org = origin(sys.argv[1])
    poses = fixed_poses(org)
    h = ['// Generated by test/bike_poses.py.', '#define POSE_COUNT %d' % len(poses),
         '#define POSE_HOLD %d' % HOLD, '#define POSE_LEVEL %d' % LEVEL,
         '#define POSE_OBJS %d' % len(OBJECTS), '',
         'typedef struct {', '\ts32 body_x, body_y;', '\tu16 body_a;',
         '\ts32 w0x, w0y, w1x, w1y;', '\tu16 w0a, w1a;', '\ts32 rx, ry, hx, hy;',
         '\tu16 turned, turn, volt, volt1;', '\ts16 cam_x, cam_y;', '} pose_t;', '',
         'static const pose_t Poses[POSE_COUNT] = {']
    for p in poses:
        v = (p.body[0], p.body[1], p.body_a, p.wheel[0][0], p.wheel[0][1], p.wheel[1][0],
             p.wheel[1][1], p.wheel_a[0], p.wheel_a[1], p.rider[0], p.rider[1], p.head[0],
             p.head[1], p.turned, p.turn, p.volt, p.volt1, p.cam[0], p.cam[1])
        h.append('\t{ %s },' % ', '.join(str(x) for x in v))
    h += ['};', '', 'static const s32 Objs[POSE_OBJS][6] = {']
    for o in objects(org):
        h.append('\t{ %d, %d, %d, %d, %d, %d },' % o)
    h.append('};')
    with open(sys.argv[2], 'w') as f:
        f.write('\n'.join(h) + '\n')


if __name__ == '__main__':
    main()
