"""The physics in the ROM (test/snes_phys.c) against its C description on
the host (test/physdump), to the bit, and the time of the steps.

  physrom.py gen CASES OUT.h
      the cases for the test ROM (build/gen/phys_testcases.h)
  physrom.py run ROM PHYSDUMP GEN_DIR CASES [--full N] [--out DIR]
      runs the ROM in Mesen 2 (test/mesen.py), the cases on the host,
      compares their logs step by step and prints the master clocks of
      phys_step (typical and worst) for each case. With --full N the whole
      state of 160 steps of case N (from its step --from K) is compared
      too, field by field.

The exit status is 1 if the logs differ.
"""

import argparse
import os
import struct
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mesen  # noqa: E402

KEYS = {'G': 1, 'B': 2, 'R': 4, 'L': 8}
WARP = 64       # an item W<n>: the front wheel onto object n
LEAVE = 32      # an item X: the bike 2000 m to the right


def read_cases(path):
    cases = []
    for line in open(path):
        line = line.split('#')[0].strip()
        if not line:
            continue
        parts = line.split()
        lev = int(parts[0])
        items = []
        for it in parts[1:]:
            keys = it.rstrip('0123456789')
            n = int(it[len(keys):] or 1)
            if keys == 'W':
                items.append((WARP, n))
                continue
            if keys == 'X':
                items.append((LEAVE, 0))
                continue
            inp = sum(KEYS.get(k, 0) for k in keys) | (128 if 'T' in keys else 0)
            items.append((inp, max(n, 1)))
        cases.append((lev, items, line))
    return cases


def nsteps(items):
    return sum(k for i, k in items if not i & (WARP | LEAVE))


def gen(cases_path, out):
    cases = read_cases(cases_path)
    items = [it for _, its, _ in cases for it in its]
    lines = ['// Generated by test/physrom.py from %s.' % os.path.basename(cases_path),
             '#define PT_NCASES %d' % len(cases),
             'static const u16 pt_case_level[] = { %s };' % ', '.join(str(c[0]) for c in cases)]
    first = []
    k = 0
    for _, its, _ in cases:
        first.append(k)
        k += len(its)
    lines.append('static const u16 pt_case_first[] = { %s };' % ', '.join(map(str, first)))
    lines.append('static const u16 pt_case_items[] = { %s };' % ', '.join(str(len(c[1])) for c in cases))
    lines.append('static const u8 pt_item_input[] = { %s };' % ', '.join(str(i) for i, _ in items))
    lines.append('static const u16 pt_item_count[] = { %s };' % ', '.join(str(n) for _, n in items))
    with open(out, 'w') as f:
        f.write('\n'.join(lines) + '\n')


LUA = r'''
local syms = { go = %d, full = %d, done = %d, step = %d, ret = %d, steps = %d }
local logt = {}
local total = 0
local last16 = 0
local function pull()
  local s16 = emu.read(syms.steps, emu.memType.snesMemory) + 256 * emu.read(syms.steps + 1, emu.memType.snesMemory)
  local d = (s16 - last16) %% 65536
  last16 = s16
  for i = 1, d do
    local a = 0x7F0000 + (total %% 10922) * 6
    local b = {}
    for j = 0, 5 do b[#b + 1] = string.char(emu.read(a + j, emu.memType.snesMemory)) end
    logt[#logt + 1] = table.concat(b)
    total = total + 1
  end
end
local started = false
local t0 = 0
local stats = {}
local case = 0
local n = 0
emu.addMemoryCallback(function()
  t0 = emu.getMasterClock()
end, emu.callbackType.exec, syms.step, syms.step)
local fullbytes = {}
local fullsteps = 0
local fullfrom = %d
local function rd(addr, len)
  for i = 0, len - 1 do fullbytes[#fullbytes + 1] = string.char(emu.read(addr + i, emu.memType.snesMemory)) end
end
emu.addMemoryCallback(function()
  local d = emu.getMasterClock() - t0
  if n >= fullfrom and fullsteps < 160 then
    fullsteps = fullsteps + 1
    rd(%d, 142)
    rd(%d, 52)
    rd(%d, 2) rd(%d, 2) rd(%d, 2) rd(%d, 2) rd(%d, 2) rd(%d, 1) rd(%d, 1)
    rd(%d, 2)
    rd(%d, 12)
  end
  n = n + 1
  stats[#stats + 1] = d
end, emu.callbackType.exec, syms.ret, syms.ret)
emu.addEventCallback(function()
  if not started and frame >= 3 then
    started = true
    emu.write(syms.full, %d, emu.memType.snesMemory)
    emu.write(syms.full + 1, %d, emu.memType.snesMemory)
    emu.write(syms.go, 1, emu.memType.snesMemory)
  end
  if started then pull() end
  if started and emu.read(syms.done, emu.memType.snesMemory) == 1 then
    pull()
    local t = {}
    for i = 1, #stats do t[#t + 1] = tostring(stats[i]) end
    out("CLK", "clocks.txt", table.concat(t, " "))
    out("LOG", "log.bin", table.concat(logt))
    out("FULL", "full.bin", table.concat(fullbytes))
    emu.stop(0)
  end
end, emu.eventType.endFrame)
'''


def run(args):
    cases = read_cases(args.cases)
    syms = mesen.read_symbols(args.rom)
    os.makedirs(args.out, exist_ok=True)
    # The host first: how many steps each case takes.
    host_log = os.path.join(args.out, 'host_log.bin')
    host_full = os.path.join(args.out, 'host_full.bin')
    cmd = [args.physdump, args.gen, args.cases, host_log]
    if args.full is not None:
        cmd += [str(args.full), host_full, str(args.full_from)]
    subprocess.run(cmd, check=True)
    host = open(host_log, 'rb').read()
    counts = []
    pos = 0
    for lev, items, line in cases:
        n = 0
        while pos + 6 <= len(host):
            ev = struct.unpack_from('<H', host, pos)[0]
            pos += 6
            n += 1
            if ev & 3 or n >= nsteps(items):
                break
        counts.append(n)
    lua = os.path.join(args.out, 'physrom.lua')
    full = args.full if args.full is not None else 0xFFFF
    first = sum(counts[:args.full]) + args.full_from if args.full is not None else 1 << 30
    with open(lua, 'w') as f:
        f.write(LUA % (syms['phys_test_go'], syms['phys_test_full'], syms['phys_test_done'],
                       syms['phys_step'], syms['phys_step_ret'], syms['phys_test_steps'], first,
                       syms['phys_dpa'], syms['phys_view'], syms['phys_bump'], syms['phys_eaten'],
                       syms['phys_friction'], syms['phys_wheel_omega'], syms['phys_apples_left'],
                       syms['phys_volt_age'], syms['phys_volt1'], syms['tcc__r0'],
                       syms['phys_dpa'] + 142,
                       full & 255, full >> 8))
    mesen.run(args.rom, 'W200000', args.out, lua=lua, timeout=3600)
    rom_log = open(os.path.join(args.out, 'log.bin'), 'rb').read()
    rom_full = open(os.path.join(args.out, 'full.bin'), 'rb').read()
    clocks = [int(x) for x in open(os.path.join(args.out, 'clocks.txt')).read().split()] \
        if os.path.exists(os.path.join(args.out, 'clocks.txt')) else []
    # Compare step by step, case by case:
    ok = True
    pos = 0
    step_case = []
    for c, (lev, items, line) in enumerate(cases):
        n = 0
        while pos + 6 <= len(host):
            ev = struct.unpack_from('<H', host, pos)[0]
            if host[pos:pos + 6] != rom_log[pos:pos + 6]:
                if ok:
                    print('case %d (level %d, %s): step %d differs: host %s rom %s' % (
                        c, lev, line[:50], n, host[pos:pos + 6].hex(), rom_log[pos:pos + 6].hex()))
                ok = False
            pos += 6
            n += 1
            step_case.append(c)
            if ev & 3 or n >= nsteps(items):
                break
    print('%d steps compared: %s' % (pos // 6, 'the same' if ok else 'DIFFERENT'))
    # The master clocks of phys_step, by case:
    if clocks:
        print('master clocks of phys_step: case: median / 90%% / worst (steps)')
        allc = []
        for c, (lev, items, line) in enumerate(cases):
            cc = sorted(clocks[i] for i in range(min(len(clocks), len(step_case))) if step_case[i] == c)
            if not cc:
                continue
            allc += cc
            print('  %2d level %2d: %6d / %6d / %6d (%d)  %s' % (
                c, lev, cc[len(cc) // 2], cc[int(len(cc) * 0.9)], cc[-1], len(cc), line[:40]))
        allc.sort()
        print('  all: %d / %d / %d' % (allc[len(allc) // 2], allc[int(len(allc) * 0.9)], allc[-1]))
        # The steps of a frame of the game: a quick step (2, 6, 10... of a
        # case) and the next one together, and the other (full) steps:
        pairs, full = [], []
        k = 0
        for i in range(min(len(clocks), len(step_case))):
            k = k + 1 if i and step_case[i] == step_case[i - 1] else 0
            if k % 4 == 2 and i + 1 < len(clocks) and step_case[i + 1] == step_case[i]:
                pairs.append(clocks[i] + clocks[i + 1])
            elif k % 4 != 3:
                full.append(clocks[i])
        for name, v in (('one full step', full), ('a quick and a full step', pairs)):
            if v:
                v.sort()
                print('  %s: %d / %d / %d' % (name, v[len(v) // 2], v[int(len(v) * 0.9)], v[-1]))
    if args.full is not None:
        FROM[0] = args.full_from
        hf = open(host_full, 'rb').read()
        compare_full(hf, rom_full[:len(hf)])
    return ok


FIELDS = []
for _name in ('body', 'kor2', 'kor4'):
    for _f in ('rx', 'ry', 'vx', 'vy', 'a', 'w'):
        FIELDS.append(('%s.%s' % (_name, _f), 4))
FIELDS += [('rider_x', 4), ('rider_y', 4), ('rider_vx', 4), ('rider_vy', 4), ('head_x', 4),
           ('head_y', 4), ('defl0', 4), ('defl1', 4), ('volt_w0', 4), ('volt_w1', 4),
           ('roll0.s', 4), ('roll0.nx', 2), ('roll0.ny', 2), ('roll0.on', 1), ('pad', 1),
           ('roll1.s', 4), ('roll1.nx', 2), ('roll1.ny', 2), ('roll1.on', 1), ('pad', 1),
           ('volt_on0', 1), ('volt_on1', 1), ('volt_t0', 1), ('volt_t1', 1), ('last_volt', 1),
           ('turned', 1), ('gravity', 1), ('brake_was', 1), ('volt1', 1), ('apples', 1),
           ('view', 52), ('bump', 2), ('eaten', 2), ('friction', 2), ('omega', 2), ('left', 2),
           ('volt_age', 1), ('volt1o', 1), ('ev', 2), ('cs22', 4), ('sn22', 4), ('cs', 2), ('sn', 2)]


FROM = [0]


def compare_full(host, rom):
    n = len(host) // 220
    for s in range(n):
        h, r = host[s * 220:(s + 1) * 220], rom[s * 220:(s + 1) * 220]
        if h == r:
            continue
        off = 0
        diffs = []
        for name, size in FIELDS:
            if name == 'view':
                hv = bytearray(h[off:off + size])
                rv = bytearray(r[off:off + size])
                for j in (10, 11, 50, 51):
                    hv[j] = rv[j] = 0
                if hv != rv:
                    diffs.append('view %s / %s' % (hv.hex(), rv.hex()))
            elif name != 'pad' and h[off:off + size] != r[off:off + size]:
                hv = int.from_bytes(h[off:off + size], 'little', signed=True)
                rv = int.from_bytes(r[off:off + size], 'little', signed=True)
                diffs.append('%s host %d rom %d' % (name, hv, rv))
            off += size
        if diffs:
            print('full step %d: %s' % (s + FROM[0], '; '.join(diffs)))
            return
    print('full: the %d steps are the same' % n)


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest='cmd')
    g = sub.add_parser('gen')
    g.add_argument('cases')
    g.add_argument('out')
    r = sub.add_parser('run')
    r.add_argument('rom')
    r.add_argument('physdump')
    r.add_argument('gen')
    r.add_argument('cases')
    r.add_argument('--full', type=int)
    r.add_argument('--from', dest='full_from', type=int, default=0)
    r.add_argument('--out', default='build/physrom')
    a = ap.parse_args()
    if a.cmd == 'gen':
        gen(a.cases, a.out)
    elif a.cmd == 'run':
        sys.exit(0 if run(a) else 1)
    else:
        ap.print_help()


if __name__ == '__main__':
    main()
