#!/usr/bin/env python3
"""Exact scalar/vector816 assembly with the existing PVSnesLib struct ABI.

These routines replace nested C word loops and memcpy calls. Parameters are
unchanged: scalar results use a hidden far destination at stack+4; scalar
arguments then start at+8. Integer-return functions start arguments at+4.
A/X/Y and compiler scratch registers are caller-saved; D/DB stay unchanged.
No PPU registers or shared multiplication latch are touched.
"""
import argparse
from pathlib import Path


FUNCTIONS=['wp_add','wp_sub','wp_neg','wp_fabs','wp_floor','wp_int','wp_to_int',
           'wp_eq','wp_ne','wp_lt','wp_gt','wp_le','wp_ge','wp_vec_make',
           'wp_add_v','wp_sub_v','wp_forgatas90fokkal']


def generate(bits=44):
    if bits not in (40,44):raise ValueError('Only Q40/Q44 are supported')
    out=['; Generated by test/wide_fast_scalar_gen.py; do not edit.',
         '.accu 16','.index 16',
         '.SECTION ".wide_fast_scalar_text" SUPERFREE']
    def emit(*lines):out.extend(lines)
    def destination():
        emit('lda 4,s','sta.b tcc__r0','lda 6,s','sta.b tcc__r0h')
    def copy(src,dst,count):
        for offset in range(0,count,2):emit('ldy #'+str(dst+offset),'lda '+str(src+offset)+',s','sta.b [tcc__r0],y')
    def arithmetic(a,b,dst,subtract=False,negate=False):
        emit('sec' if subtract else 'clc')
        for offset in range(0,8,2):
            emit('ldy #'+str(dst+offset),'lda #0' if negate else 'lda '+str(a+offset)+',s',
                 ('sbc ' if subtract else 'adc ')+str(b+offset)+',s')
            if offset==6:emit('bvc +','jmp wide_fast_scalar_error','+')
            emit('sta.b [tcc__r0],y')
    for name,subtract in [('wp_add',False),('wp_sub',True)]:
        emit(name+':');destination();arithmetic(8,16,0,subtract);emit('rtl')
    emit('wp_neg:');destination();arithmetic(0,8,0,True,True);emit('rtl')
    emit('wp_fabs:','lda 14,s','bpl +','jml wp_neg','+')
    destination();copy(8,0,8);emit('rtl')
    emit('wp_floor:');destination()
    for offset in (0,2):emit('ldy #'+str(offset),'lda #0','sta.b [tcc__r0],y')
    emit('ldy #4','lda 12,s','and #'+str((65535<<(bits-32))&65535),'sta.b [tcc__r0],y')
    copy(14,6,2);emit('rtl')
    emit('wp_int:');destination()
    for offset in (0,2):emit('ldy #'+str(offset),'lda #0','sta.b [tcc__r0],y')
    emit('lda 8,s','xba','and #$ff00')
    for _ in range(bits-40):emit('asl a')
    emit('ldy #4','sta.b [tcc__r0],y','lda 8,s')
    for _ in range(48-bits):emit('lsr a')
    emit('ldy #6','sta.b [tcc__r0],y','lda 8,s','bpl +',
         'lda.b [tcc__r0],y','ora #'+str((65535<<(bits-32))&65535),'sta.b [tcc__r0],y','+','rtl')
    emit('wp_to_int:','lda 10,s')
    for _ in range(48-bits):emit('asl a')
    emit('sta.b tcc__r0','lda 8,s')
    for _ in range(bits-32):emit('lsr a')
    emit('ora.b tcc__r0','sta.b tcc__r0','stz.b tcc__r0h',
         'lda 10,s','bpl +','lda 8,s','and #'+str((1<<(bits-32))-1),
         'ora 6,s','ora 4,s','beq +','inc.b tcc__r0','+','rtl')
    predicates={'eq':['beq'],'ne':['bne'],'lt':['bmi'],
                'gt':['cmp #1','beq'],'le':['cmp #1','bne'],'ge':['cmp #$ffff','bne']}
    for relation,lines in predicates.items():
        emit('wp_'+relation+':','jsr wide_fast_scalar_compare','stz.b tcc__r0','stz.b tcc__r0h')
        emit(*lines[:-1],lines[-1]+' +','rtl','+','lda #1','sta.b tcc__r0','rtl')
    emit('wide_fast_scalar_compare:','lda 12,s','eor 20,s','bpl +',
         'lda 12,s','bmi wide_fast_scalar_less','bra wide_fast_scalar_greater','+')
    for offset in (6,4,2,0):
        emit('lda '+str(6+offset)+',s','cmp '+str(14+offset)+',s',
             'bcc wide_fast_scalar_less','bne wide_fast_scalar_greater')
    emit('lda #0','rts','wide_fast_scalar_less:','lda #$ffff','rts',
         'wide_fast_scalar_greater:','lda #1','rts')
    emit('wp_vec_make:');destination();copy(8,0,16);emit('rtl')
    for name,subtract in [('wp_add_v',False),('wp_sub_v',True)]:
        emit(name+':');destination()
        arithmetic(8,24,0,subtract);arithmetic(16,32,8,subtract);emit('rtl')
    emit('wp_forgatas90fokkal:');destination();arithmetic(0,16,0,True,True);copy(8,8,8);emit('rtl')
    emit('wide_fast_scalar_error:','lda #1','sta.l wp_native_error','-','bra -','.ENDS')
    measured=[];returns=0
    for line in out:
        if line=='rtl':
            measured.append('wide_fast_scalar_return_'+str(returns)+':');returns+=1
        measured.append(line)
    return '\n'.join(measured)+'\n'


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--bits',type=int,choices=(40,44),default=44)
    ap.add_argument('--out',type=Path,required=True)
    a=ap.parse_args();a.out.parent.mkdir(parents=True,exist_ok=True);a.out.write_text(generate(a.bits))
    print(a.out)


if __name__=='__main__':main()
