#!/usr/bin/env python3
"""Generate exact byte products for the experimental native force kernel."""

import argparse
from pathlib import Path


SPRING_COEFFICIENT = 32009962
DAMPER_COEFFICIENT = 586263036
TABLE_BYTES = 4 * 256 * 8


def generate(path):
    lines = [
        "; Generated by test/wide_force_gen.py; exact signed64 products.",
        '.SECTION ".wide_force_tables" SUPERFREE',
    ]
    for name, coefficient, signed in (
        ("s_unsigned", SPRING_COEFFICIENT, False),
        ("s_signed", SPRING_COEFFICIENT, True),
        ("d_unsigned", DAMPER_COEFFICIENT, False),
        ("d_signed", DAMPER_COEFFICIENT, True),
    ):
        lines.append("wide_force_" + name + ":")
        for byte in range(256):
            operand = byte - 256 if signed and byte >= 128 else byte
            product = operand * coefficient
            words = [(product >> (16 * i)) & 65535 for i in range(4)]
            lines.append(".dw " + ",".join(map(str, words)))
    lines.append(".ENDS")
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    return path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.output)


if __name__ == "__main__":
    main()
