// Host-only Hi Flyer experiment. Reuse physcmp's level loader helpers and
// fixed point conversion; its command-line entry point is not called here.
#define main physcmp_command_main
#include "physcmp.c"
#undef main

static rbike Reference;

int probe_level( const char* path ) {
	FILE* f = fopen( path, "r" );
	double sx, sy;
	Nf = 0;
	if( !f ) return 0;
	if( fscanf( f, "%d %lf %lf", &Nr, &sx, &sy ) != 3 || Nr < 0 || Nr > 4000 ) {
		fclose( f );
		return 0;
	}
	for( int i = 0; i < Nr; i++ ) {
		rseg* s = &Rsegs[i];
		if( fscanf( f, "%lf %lf %lf %lf", &s->r.x, &s->r.y, &s->v.x, &s->v.y ) != 4 ||
				Nf+(int)(hypot( s->v.x, s->v.y )/8.0)+1 > 8000 ) {
			fclose( f );
			return 0;
		}
		addfseg( s->r.x+OFS, s->r.y+OFS, s->v.x, s->v.y );
	}
	fclose( f );
	return 1;
}

// State layout: body, wheel 0, wheel 1 each have x,y,vx,vy,angle,omega;
// then rider x,y,vx,vy, head x,y, turned, and two brake spring angles.
void probe_init( const double* s ) {
	ref_init( &Reference, 0, 0 );
	rcircle* c[3] = { &Reference.body, &Reference.wheel[0], &Reference.wheel[1] };
	for( int i = 0; i < 3; i++ ) {
		c[i]->r.x = s[6*i]; c[i]->r.y = s[6*i+1];
		c[i]->v.x = s[6*i+2]; c[i]->v.y = s[6*i+3];
		c[i]->alfa = s[6*i+4]; c[i]->omega = s[6*i+5];
	}
	Reference.rider_r.x = s[18]; Reference.rider_r.y = s[19];
	Reference.rider_v.x = s[20]; Reference.rider_v.y = s[21];
	Reference.turned = (int)s[24];
	double a = Reference.body.alfa, hx = Reference.turned ? 0.09 : -0.09;
	Reference.head.x = Reference.rider_r.x+cos(a)*hx-sin(a)*0.63;
	Reference.head.y = Reference.rider_r.y+sin(a)*hx+cos(a)*0.63;
	ph_init( 0, 0 );
	tofix( &Reference );
	Bike.head_x = lround( (Reference.head.x+OFS)*PH_S );
	Bike.head_y = lround( (Reference.head.y+OFS)*PH_S );
}

int probe_step( int fixed, int input, double now, double dt ) {
	if( fixed ) return ph_step( (uint8_t)input );
	return ref_step( &Reference, Rsegs, Nr, now, dt,
		input & IN_GAS, input & IN_BRAKE, input & IN_VOLT_RIGHT, input & IN_VOLT_LEFT );
}

void probe_get( int fixed, double* s ) {
	rcircle* c[3] = { &Reference.body, &Reference.wheel[0], &Reference.wheel[1] };
	circle_t* f[3] = { &Bike.body, &Bike.wheel[0], &Bike.wheel[1] };
	for( int i = 0; i < 3; i++ ) {
		if( fixed ) {
			s[6*i] = f[i]->rx/PH_S-OFS; s[6*i+1] = f[i]->ry/PH_S-OFS;
			s[6*i+2] = f[i]->vx/PH_VS; s[6*i+3] = f[i]->vy/PH_VS;
			s[6*i+4] = (int32_t)f[i]->alfa/PH_AN; s[6*i+5] = f[i]->omega/PH_WS;
		} else {
			s[6*i] = c[i]->r.x; s[6*i+1] = c[i]->r.y;
			s[6*i+2] = c[i]->v.x; s[6*i+3] = c[i]->v.y;
			s[6*i+4] = c[i]->alfa; s[6*i+5] = c[i]->omega;
		}
	}
	if( fixed ) {
		s[18] = Bike.rider_x/PH_S-OFS; s[19] = Bike.rider_y/PH_S-OFS;
		s[20] = Bike.rider_vx/PH_VS; s[21] = Bike.rider_vy/PH_VS;
		s[22] = Bike.head_x/PH_S-OFS; s[23] = Bike.head_y/PH_S-OFS;
		s[24] = Bike.turned;
		for( int k = 0; k < 2; k++ )
			s[25+k] = Bike.brake_was ? (int32_t)(Bike.wheel[k].alfa-Bike.body.alfa-Bike.dbrake[k])/PH_AN : 0;
	} else {
		s[18] = Reference.rider_r.x; s[19] = Reference.rider_r.y;
		s[20] = Reference.rider_v.x; s[21] = Reference.rider_v.y;
		s[22] = Reference.head.x; s[23] = Reference.head.y;
		s[24] = Reference.turned;
		for( int k = 0; k < 2; k++ )
			s[25+k] = Reference.brake_was ? Reference.wheel[k].alfa-Reference.body.alfa-Reference.dbrake[k] : 0;
	}
}

double probe_dt( void ) { return PH_H; }

// Emit a seed for asmcmp in the SDK simulator. The simulator uses the same
// +300 m translation as the host experiment, generated by hyflyer.py.
void probe_seed( const char* path ) {
	FILE* f = fopen( path, "w" );
	if( !f ) return;
	circle_t* c[3] = { &Bike.body, &Bike.wheel[0], &Bike.wheel[1] };
	const char* names[3] = { "body", "wheel[0]", "wheel[1]" };
	fprintf( f, "ph_init(0,0);\n" );
	for( int i = 0; i < 3; i++ ) {
		fprintf( f, "Bike.%s.rx=%ldL; Bike.%s.ry=%ldL;\n", names[i], (long)c[i]->rx, names[i], (long)c[i]->ry );
		fprintf( f, "Bike.%s.vx=%d; Bike.%s.vy=%d;\n", names[i], c[i]->vx, names[i], c[i]->vy );
		fprintf( f, "Bike.%s.alfa=%luUL; Bike.%s.omega=%d;\n", names[i], (unsigned long)c[i]->alfa, names[i], c[i]->omega );
	}
	fprintf( f, "Bike.rider_x=%ldL; Bike.rider_y=%ldL; Bike.rider_vx=%d; Bike.rider_vy=%d;\n",
		(long)Bike.rider_x, (long)Bike.rider_y, Bike.rider_vx, Bike.rider_vy );
	fprintf( f, "Bike.head_x=%ldL; Bike.head_y=%ldL; Bike.turned=%d;\n", (long)Bike.head_x, (long)Bike.head_y, Bike.turned );
	fclose( f );
}
