"""Writes the lines of a level (from levtext.py) as a C table for the tests
in the simulator: in u (1 m = 1024), moved into positive coordinates, cut
into parts of at most 8 m like physcmp.c does, with the start in F.

  simlines.py LEVEL.txt > simlines.h
"""

import math
import os
import sys


def iround(v):
    return int(math.floor(v + 0.5))


def main():
    with open(sys.argv[1]) as f:
        n, sx, sy = f.readline().split()
        lines = [tuple(map(float, f.readline().split())) for _ in range(int(n))]
    sx, sy = float(sx), float(sy)
    # Whole meters, so that every coordinate is at least 1 m:
    ox = max(1, 1 + math.ceil(-min(min(x, x + dx) for x, y, dx, dy in lines)))
    oy = max(1, 1 + math.ceil(-min(min(y, y + dy) for x, y, dx, dy in lines)))
    print('// Generated by simlines.py from %s, moved by (%d, %d) m.' % (
        os.path.basename(sys.argv[1]), ox, oy))
    print('#define SIM_START_X %dL' % iround((sx + ox) * 262144))
    print('#define SIM_START_Y %dL' % iround((sy + oy) * 262144))
    print('#define SIM_LINES \\')
    for x, y, dx, dy in lines:
        x, y = x + ox, y + oy
        parts = int(math.hypot(dx, dy) / 8) + 1
        for i in range(parts):
            px, py = iround((x + dx * i / parts) * 1024), iround((y + dy * i / parts) * 1024)
            qx = iround((x + dx * (i + 1) / parts) * 1024)
            qy = iround((y + dy * (i + 1) / parts) * 1024)
            ddx, ddy = qx - px, qy - py
            ll = math.hypot(ddx, ddy)
            if ll < 0.5:
                continue
            print('\t{ %d, %d, %d, %d, %d, %d, %d }, \\' % (
                px, py, ddx, ddy, iround(ddx / ll * 16384), iround(ddy / ll * 16384), iround(ll)))
    print()


if __name__ == '__main__':
    main()
