"""Writes build/gen/levels.h and levels.asm: how many internal levels the
elma.res has, their names, and the geometry of each (levgeom.py).

  gen_levels.py ELMA_RES OUT_DIR
"""

import os
import sys

import elmadata
import levgeom


def main():
    res = elmadata.Resource(sys.argv[1])
    out = sys.argv[2]
    levels = elmadata.internal_levels(res)
    h = ['// Generated by tools/gen_levels.py from %s.' % os.path.basename(sys.argv[1]),
         '#ifndef LEVELS_H', '#define LEVELS_H', '',
         '#define LEVEL_COUNT %d' % len(levels),
         '#define LEVEL_SHAREWARE %d' % int(res.shareware),
         '// Pixels a meter of the level pixels, times 256 (levgeom.py):',
         '#define PX_PER_M_NUM %d' % levgeom.PX_PER_M_NUM, '',
         'typedef struct {',
         '\tchar name[51];       // as in the menus of the game',
         '} level_name_t;', '',
         '// Origin of the level pixels (16.16 meters) and the size of the level',
         '// in them, by level:',
         'typedef struct {',
         '\ts32 org_x, org_y;',
         '\tu16 width, height;',
         '} level_geom_t;', '',
         'extern const level_name_t level_names[LEVEL_COUNT];',
         'extern const level_geom_t level_geom[LEVEL_COUNT];', '',
         '#endif']
    a = ['; Generated by tools/gen_levels.py.', '.include "hdr.asm"', '',
         '.SECTION ".level_names" SUPERFREE', 'level_names:']
    for lev in levels:
        name = lev.name.encode('latin-1')[:50]
        a.append('\t.db %s' % ', '.join(str(b) for b in name + b'\0' * (51 - len(name))))
    a += ['.ENDS', '', '.SECTION ".level_geom" SUPERFREE', 'level_geom:']
    for lev in levels:
        ox, oy = levgeom.origin(lev)
        w, hgt = levgeom.size_px(lev)
        a.append('\t.dl %d & $FFFFFF, %d & $FFFFFF' % (ox, oy))
        a[-1] = '\t.dd %d, %d\n\t.dw %d, %d' % (ox, oy, w, hgt)
    a += ['.ENDS', '']
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, 'levels.h'), 'w') as f:
        f.write('\n'.join(h) + '\n')
    with open(os.path.join(out, 'levels.asm'), 'w') as f:
        f.write('\n'.join(a))


if __name__ == '__main__':
    main()
