
// idot adja vissza szazadmasodpercben:
long lejatszo( recorder* prec, int replay );

void egesz( void );

void kitesz( int igen );
void kiteljeskerek( int x, int y, int sugar, double alfa = -10001.0 );
void vonalki( int x1, int y1, int x2, int y2 );
extern int ColorBG, ColorFG, ColorFG2;

void kinyom( int ertek ); // Csak teszt celokra!

extern long L;

extern szakaszok *Pszak;

extern int Kajaszam, Kajakell;

extern int Hatra;

