Elasto Mania shareware version 1.2 Copyright (C) 1997, 1998 Bal zs R¢zsa

You are welcome to distribute this program freely, as long as you don't
change it in any way. If you like Elasto Mania and continue to use it,
I ask you to register. I depend on your registrations.

When you register Elasto Mania for $29.95, you will get the registered
version, which has 26 more new levels and the full editor. Please add $4 for
shipping. Registered users of previous versions can upgrade to version 1.2
for free, read order.txt.

To register, send a check or money order payable to: Pik A Program (tm)
													 13 Saint Marks Place
                                                     NY, NY 10003
                                                     USA
For Credit Card orders, call TOLL FREE (ORDERS ONLY) 1-800-867-3447.
For Online Compuserve orders, GO SWREG (product ID.: 12817).
You can register and immediately download Elastomania on the WEB at
												http://www.pik.com

If you have any question about Elasto Mania, visit www.elastomania.com
or send an e-mail to:     feedback@elastomania.com



Press a key!
