"""Builds the data of the NES version from the game data:

  build.py --res elma.res [--lev FILE.lev ...] --out DIR

writes into DIR
  levels.bin   the levels, for the data banks of the PRG-ROM
  levdata.s    puts levels.bin into the banks
  levels.c     the table of the levels
  chr.bin      the CHR-ROM: tiles of the levels, the menus and the sprites
  chr.s        puts chr.bin into the CHR-ROM
"""

import argparse
import os
import sys

import numpy as np

import elmadata
import gfx
import levconv
import pack

# The banks of the PRG-ROM for the levels and the sprites, then the banks of
# the physics and of the menus (the last three banks hold the rest of the
# program):
DATA_BANKS = 58
PHYS_BANK = 59
MENU_BANK = 60

# Banks of the CHR-ROM, in 1 KB. Background tiles go in 2 KB pairs.
CHR_BG_COMMON = 0      # tiles 0..127 of the levels
CHR_BG_MENU = 2        # 4 KB of the menus
CHR_SPR_MISC = 6       # wheels and objects
CHR_SPR_HUD = 7        # digits and letters of the sprites
CHR_BG_LEVEL = 8       # tiles 128..255 of each level, 2 KB each
CHR_SPR_BIKE = 128     # the bike and the rider at 64 angles
CHR_KB = 256


def tile_bytes(t):
    """A tile of 8x8 colors (0..3) in the 2 bit planes of the NES."""
    t = np.asarray(t, np.uint8)
    lo = np.packbits((t & 1).astype(np.uint8), axis=1)[:, 0]
    hi = np.packbits((t >> 1).astype(np.uint8), axis=1)[:, 0]
    return bytes(lo) + bytes(hi)


def tiles_bytes(tiles, count):
    out = bytearray()
    for t in tiles:
        out += tile_bytes(t) if t is not None else bytes(16)
    out += bytes(16 * count - len(out))
    return bytes(out)


def c_string(s):
    s = s.encode('ascii', 'replace').decode('ascii')
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def load_levels(args):
    levs = []
    if args.res:
        levs += elmadata.internal_levels(elmadata.Resource(args.res))
    for path in args.lev or []:
        lev = elmadata.load_lev(path)
        if not lev.name:
            lev.name = os.path.splitext(os.path.basename(path))[0]
        levs.append(lev)
    return levs


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--res', help='elma.res of the game, for its levels')
    ap.add_argument('--lev', nargs='*', help='level files to add')
    ap.add_argument('--out', required=True)
    args = ap.parse_args()
    levs = load_levels(args)
    if not levs:
        sys.exit("No levels: give the elma.res of the game or level files.")
    max_levels = (CHR_SPR_BIKE - CHR_BG_LEVEL) // 2
    if len(levs) > max_levels:
        print("Only the first %d levels fit." % max_levels)
        levs = levs[:max_levels]
    os.makedirs(args.out, exist_ok=True)

    space = pack.Space(DATA_BANKS)
    chr_rom = bytearray(CHR_KB * 1024)
    common = levconv.common_tiles()
    chr_rom[CHR_BG_COMMON * 1024:(CHR_BG_COMMON + 2) * 1024] = \
        tiles_bytes(common[:128], 128)
    rows = []
    for i, lev in enumerate(levs):
        conv = levconv.Converted(lev)
        placed = pack.place_level(space, conv)
        bank = CHR_BG_LEVEL + 2 * i
        chr_rom[bank * 1024:(bank + 2) * 1024] = \
            tiles_bytes(common[128:] + conv.extras, 128)
        rows.append((conv, placed, bank))
        note = ''
        if conv.approximated:
            note = ', %d corner tiles drawn approximately' % conv.approximated
        print('%2d %-24s %3dx%-3d tiles, %4d lines%s'
              % (i + 1, conv.name, conv.w, conv.h, conv.n_segments, note))
    print('Levels: %d KB of %d KB' % (len(space.data) // 1024,
                                      space.limit // 1024))
    gfx.build(chr_rom, CHR_BG_MENU, CHR_SPR_MISC, CHR_SPR_HUD, CHR_SPR_BIKE,
              args.out, space)
    with open(os.path.join(args.out, 'banks.h'), 'w') as f:
        f.write('// Generated by build.py.\n#define PHYS_BANK %d\n'
                '#define MENU_BANK %d\n' % (PHYS_BANK, MENU_BANK))

    with open(os.path.join(args.out, 'levels.bin'), 'wb') as f:
        f.write(space.data)
    banks = -(-len(space.data) // pack.BANK)
    with open(os.path.join(args.out, 'levdata.s'), 'w') as f:
        f.write('; Generated by build.py: the levels in the data banks.\n')
        for b in range(banks):
            n = min(pack.BANK, len(space.data) - b * pack.BANK)
            f.write('.section .prg_rom_%d,"aR",@progbits\n' % b)
            f.write('.incbin "%s", %d, %d\n' % (os.path.abspath(
                os.path.join(args.out, 'levels.bin')), b * pack.BANK, n))
    with open(os.path.join(args.out, 'chr.bin'), 'wb') as f:
        f.write(chr_rom)
    with open(os.path.join(args.out, 'chr.s'), 'w') as f:
        f.write('; Generated by build.py: the CHR-ROM.\n')
        f.write('.section .chr_rom,"a",@progbits\n.incbin "%s"\n'
                % os.path.abspath(os.path.join(args.out, 'chr.bin')))
    with open(os.path.join(args.out, 'levels.c'), 'w') as f:
        f.write('// Generated by build.py: the levels, in the bank of the menus.\n')
        f.write('#include "levels.h"\n\n')
        f.write('#pragma clang section rodata=".prg_rom_%d.rodata"\n\n' % MENU_BANK)
        for i, (conv, p, bank) in enumerate(rows):
            f.write('static const char Name%02d[] = %s;\n' % (i, c_string(conv.name[:LEVEL_NAME])))
        f.write('\nconst level_t Levels[] = {\n')
        for i, (conv, p, bank) in enumerate(rows):
            f.write('\t{ Name%02d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d },\n' % (
                i, conv.w, conv.h, p.columns, p.map,
                p.segments, conv.gw, conv.gh, p.grid_rows, p.grid, p.objects,
                conv.start[0], conv.start[1], bank))
        f.write('};\n\nconst uint8_t Level_count = %d;\n' % len(rows))

LEVEL_NAME = 22

if __name__ == '__main__':
    main()
