"""Writes src/physconst.h, the constants of the physics as integers, for
physics.c and physics.S alike.

A constant c multiplies as KMUL: c = M/2^E with M of 8 bits (128..255),
which takes a multiplication of 16 by 8 bits.
"""

import math
import os
import sys

# One step is a frame of NTSC of the game's time, which runs 0.4368 times
# as fast as the clock (182 ticks a second times 0.0024):
H = 0.4368 / 60.0988
S = 262144.0                  # F per m
AN = 16777216.0 / (2 * math.pi)  # angle units per radian
VS = S * H / 4                # velocity units per m/s (4 F per step)
WS = AN * H / 128             # angular velocity units per rad/s
BRAKE_DAMPING = 0.7

# name: (value, comment)
FACTORS = [
    ('K_X', 0.85 * 1024 / 16384,
     'the right wheel relative to the body, (0.85, -0.6) m, times cos and sin into u'),
    ('K_Y', 0.6 * 1024 / 16384, ''),
    ('SPRING_W', 1000 * H * VS / 16384,
     'wheel spring: K = 10000 N/m, wheel 10 kg; its length in r16'),
    ('SPRING_B', 50 * H * VS / 16384, 'the same on the body of 200 kg'),
    ('SPRING_T', 10000 / 60.5 * H * WS / (1024 * 16384) * 1024,
     'its torque on the body (moment of inertia 200*0.55^2), from the sum '
     'of lever arm (u) x length (r16) >> 10'),
    ('FRIC_W', 100 * H, 'damping between the wheels and the body: Sr = 1000 Ns/m'),
    ('FRIC_B', 5 * H, ''),
    ('FRIC_T', 1000 / 60.5 * H * WS / (1024 * VS) * 1024,
     'its torque, from the sum of lever arm (u) x velocity >> 10'),
    ('OMS', VS / WS / 1024 * 16384 / 16,
     'the body angular velocity, for mulq14 with a lever arm << 4 (u)'),
    ('REACT', H * VS * 1024 / (4 * 10) / 256,
     'force of a wheel torque on the axle'),
    ('TWENTIETH', 1 / 20, ''),
    ('BRAKE_A', 4000 * 2 * math.pi / 65536, 'brake: 1000 Nm/rad'),
    ('BRAKE_W', 400 * BRAKE_DAMPING / WS,
     'and 100 Nms/rad, taken 0.7 times, so that a free wheel does not swing '
     'ever wider with a step this long (the game steps 0.003 s)'),
    ('FREE', 0.25 / 0.32 * H * WS, 'a free wheel turning (moment of inertia 0.32)'),
    ('ROLL_W', WS / (VS * 0.4),
     'a wheel rolling around a contact point (moment of inertia 0.32 + 10*0.3975^2 there)'),
    ('ROLL_T', 4 * 10 * 0.4 / (H * VS), ''),
    ('ROLL_DW', 0.25 / (0.32 + 10 * 0.3975 ** 2) * H * WS, ''),
    ('ROLL_V', 0.4 * VS / WS, ''),
    ('NEW', WS / (1024 * VS) * 1024, ''),
    ('OLD', 4 * 10 / (1024 * H * VS) * 64, ''),
    ('RREST', 0.44, 'the rider: rest 0.44 m above the body, moves every other step'),
    ('RIDER_S', 250 * 2 * H * VS / 16384, 'its spring, 5 times as strong'),
    ('RIDER_F', 15 * 2 * H, 'its damping, 3 times as strong'),
    ('SEAT_NX', 0.23 / 0.54129474, 'the normal of the seat (-0.42, 0.91)'),
    ('SEAT_NY', 0.49 / 0.54129474, ''),
    ('ELLIPSE', 0.48 / 0.26, ''),
    ('H_X', 0.09 * 1024 / 16384, 'the head relative to the rider, (0.09, 0.63) m'),
    ('H_Y', 0.63 * 1024 / 16384, ''),
]

def u(m):
    return int(round(m * 1024))

INTEGERS = [
    ('R_WHEEL', u(0.4), 'sizes in u (1 m = 1024)'),
    ('R_HEAD', u(0.238), ''),
    ('BAND', u(0.005), 'the wheel is kept this much inside the ground (Belsosav)'),
    ('MERGE', u(0.1), 'contact points closer are merged (Talppontegybeolvadasitav)'),
    ('G_INT', int(10 * H * VS), 'gravity in a step, with its fraction in 1/256'),
    ('G_FRAC', int(round((10 * H * VS - int(10 * H * VS)) * 256)), ''),
    ('LOKET', int(12 * WS + 0.5), 'a volt (Loket) and what is left of it (Omegavalt)'),
    ('OMEGAVALT', int(3 * WS + 0.5), ''),
    ('VOLT_STEPS', int(0.1 / H + 1), 'a volt lasts 0.1 s (Ugroturelem*0.25)'),
    ('WHEEL_MAXW', int(110 * WS), 'highest angular velocity of the driven wheel'),
    ('ELSZ', int(0.01 * VS + 0.5), 'separation speed limit, 0.01 m/s'),
    ('VEL_1MS', int(VS + 0.5), '1 m/s'),
    ('GAS_TQ', 600 * 4, 'gas: 600 Nm, in 1/4 Nm'),
    ('F_BODY_X', int(0.85 * S), 'the bike at the start, from its left wheel, in F'),
    ('F_BODY_Y', int(0.6 * S), ''),
    ('F_WHEELBASE', int(1.7 * S), ''),
    ('F_RIDER_Y', int(1.04 * S), ''),
    ('F_HEAD_Y', int(0.63 * S), ''),
    ('SEAT_X', u(-0.35), 'where the rider may be relative to the body'),
    ('SEAT_Y', u(0.13), ''),
    ('RIDER_TOP', u(0.48), ''),
    ('RIDER_LEFT', u(-0.5), ''),
    ('RIDER_RIGHT', u(0.26), ''),
]


def factor(c):
    """M and E of c = M/2^E, M of 8 bits; E from 1 to 16."""
    e = 0
    while c * (1 << e) < 127.5:
        e += 1
    while c * (1 << e) >= 255.5:
        e -= 1
    m = int(round(c * (1 << e)))
    if not 1 <= e <= 16:
        raise ValueError(c)
    return m, e


def main():
    out = os.path.join(os.path.dirname(__file__), '..', 'src', 'physconst.h')
    lines = ['// Generated by tools/physconst.py: the constants of the physics.',
             '#ifndef PHYSCONST_H', '#define PHYSCONST_H', '']
    for name, v, comment in INTEGERS:
        if comment:
            lines.append('// ' + comment + ':')
        lines.append('#define %s %d' % (name, v))
    lines.append('')
    lines.append('// Factors c as M/2^E:')
    for name, c, comment in FACTORS:
        m, e = factor(c)
        if comment:
            lines.append('// ' + comment + ':')
        lines.append('#define C_%s_M %d' % (name, m))
        lines.append('#define C_%s_E %d' % (name, e))
    lines += ['', '#endif', '']
    with open(out, 'w') as f:
        f.write('\n'.join(lines))


if __name__ == '__main__':
    main()
